# Generated by Django 4.1.2 on 2023-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Cumilla', 'Cumilla'), ('Dhaka', 'Dhaka')], max_length=50),
        ),
    ]
