# Generated by Django 4.1.2 on 2023-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delevery', 'Cash on Delivery'), ('paypal', 'Paypal'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delevery', max_length=30),
        ),
    ]
